### ISSUE TITLE
API Key in code

### ISSUE THREAD

**Issue by garybpt** [mitesh-200228/RESUME_PARSER#1]
Hey,

Just been looking at your resume parser and spotted that you've uploaded your OpenAI Key to the repo. With. it, anyone can rock up significant bills on your card so I would highly recommend removing it. 

Gary

**Comment by garybpt** [comment]
Your embeddings.csv file also include's people names, email address, and phone numbers.

**Comment by mitesh-200228** [comment]
Don't worry, it is not working anyways, and talk about embeddings.csv, then
its dummy data.

By the way thanks for informing.

**Comment by garybpt** [comment]
Ah ok, good stuff. Just wanted to make sure you were aware.
